kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world
  - name: build image
    image: plugins/docker
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    settings:
      username: $USERNAME
      password: $PASSWORD
      dockerfile: Dockerfile.nest
      repo: azamara/drone-examples-nest