kind: pipeline
type: docker
name: nest

steps:
  - name: build image
    image: plugins/docker
    settings:
      cache_from: "azamara/drone-examples-nest:latest"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile.nest
      repo: azamara/drone-examples-nest

---

kind: pipeline
type: docker
name: gin-basic

steps:
  - name: build image
    image: plugins/docker
    settings:
      cache_from: "azamara/drone-examples-gin-basic"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile.gin-basic
      repo: azamara/drone-examples-gin-basic